name = "testpack"
author = "noname"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e6413e4c79e5cf992d09f9607899f6d298d93f4148db1a4105eb66e6de8194fc"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
