name = "testpack"
author = "noname"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "51c7460eb9a4087fc0e9f748310feef9becb658faf8a74d72f93f3b76599ade4"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
