name = "testpack"
author = "noname"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4d7f44532784e770fef4b972e1a2a2a49e8fcec43917b03079bd93df0a4149cc"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
