name = "testpack"
author = "noname"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "202c6fdb9fa4cfa0103659c0fe98282beb05cc28e3d6a4c0bc790397c7a083f0"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
