name = "testpack"
author = "noname"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fb07450cfee5730c2c93e84cb2e533724baaf80adae2638ab643a87f6b90dfb8"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
